version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: PRODUCTION
      MONGODB_HOST: mongo
      API_PORT: 3000
    command: yarn run demo
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '19006:19006'
      - '19000:19000'
    command: yarn web
    depends_on:
      - backend
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    restart: always
    ports:
      - '27017:27017'
    command: mongod --replSet ordersReplicaSet
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example