name: (RELEASE)

on:
  push:
    branches:
    - release

jobs:  
  test-build:  
    name: Upload to Cluster
    runs-on: ubuntu-latest  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  
    - name: Copy frontend files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "frontend/"
        target: "/home/ubuntu/"
    - name: Copy backend files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "backend/"
        target: "/home/ubuntu/"